// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using entrega1.Services;

#nullable disable

namespace entrega1.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221206013326_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("entrega1.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("GradeAvg")
                        .HasColumnType("double precision")
                        .HasAnnotation("Relational:JsonPropertyName", "promedio");

                    b.Property<string>("LastNames")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "apellidos");

                    b.Property<string>("Names")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "nombres");

                    b.Property<string>("Tuition")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "matricula");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("entrega1.Models.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseHrs")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "horasClase");

                    b.Property<int>("EmployeeNum")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "numeroEmpleado");

                    b.Property<string>("LastNames")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "apellidos");

                    b.Property<string>("Names")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "nombres");

                    b.HasKey("Id");

                    b.ToTable("Profesores");
                });
#pragma warning restore 612, 618
        }
    }
}
